- ecs-init/config/common.go
- packaging/amazon-linux-ami/ecs-init.spec
- Cache Agent version 1.3.1
- Read Docker endpoint from environment variable DOCKER_HOST if present
r? @euank @aaithal
> Update to support Agent 1.3.1

- .travis.yml
- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
Add default logging drivers `json-file` and `syslog`.  Also includes a commit that better-handles user-supplied environment variables.
r? @euank
> Add default logging drivers

- ecs-init/config/common.go
- ecs-init/config/default_system_paths.go
- scripts/gobuild.sh
This should help enable conditional compilation for other systems which have made different choices for the `cgroup` and `execdriver` paths.
This is intended to help with #23 if different `cgroup` and `execdriver` paths are needed there.
r? @euank
> Separate system paths for build logic control

- .travis.yml
- ecs-init/config/common.go
- ecs-init/config/default_system_paths.go
- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
- packaging/amazon-linux-ami/ecs-init.spec
- scripts/gobuild.sh
- Cache Agent version 1.5.0
- Improved merge strategy for user-supplied environment variables
- Add default supported logging drivers
r? @euank @aaithal
> Update to support Agent 1.5.0

- ecs-init/config/suse_system_paths.go
- packaging/suse/amazon-ecs-init.spec
- packaging/suse/cgroup_location.patch
I've added a build flag for SUSE for builds after 1.5.0 and adjusted the SUSE patch for the 1.5.0 tarball.
@rjschwei, can you take a look?
> Changes to SUSE packaging for 1.5.0+

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
`make test` passes. also verified that ECS Agent is started with `"NetworkMode"="Host"` on an instance with this change when I run `start ecs` and that I can ping the endpoints exposed by the agent.
r? @samuelkarp @juanrhenals @richardpen
> Start agent with --net=host

- ecs-init/cache/cache.go
- ecs-init/cache/cache_test.go
Fixes https://github.com/aws/amazon-ecs-agent/issues/420
Download the agent tarball directly into the cache directory such that there are no problems renaming the temporary download file into the final tarball name.
r? @aaithal @juanrhenals @richardpen
> cache: Download directly into cache directory

- .gitignore
- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
- ecs-init/exec/iptables/iptables.go
- ecs-init/exec/iptables/iptables_test.go
Modify netfilter Create and Remove functions to add and remove
an OUTPUT rule to redirect processes/containers that use
host's network stack to redirect credentials requests to
localhost:51679.
This is needed for ensuring that containers launched with
net=host can still talk to the credentials endpoint.
Set the ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST env var config to true
when starting the ECS Agent. This config registers the ECS Agent with
the capability to run Tasks that require Task IAM Roles when
created with 'host' network mode.
```bash
$ sudo iptables -t nat -S > pre-pre-start && sudo ./amazon-ecs-init pre-start && sudo iptables -t nat -S > post-pre-start && diff pre-pre-start post-pre-start
6a7
> -A PREROUTING -d 169.254.170.2/32 -p tcp -m tcp --dport 80 -j DNAT --to-destination …
```
> Enable Task IAM Role for containers launched with 'host' network mode.

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
Adding `CAP_NET_ADMIN` for amazon-ecs-agent
Testing
> CAP_NET_ADMIN for amazon-ecs-agent

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
This is required by the ECS Agent to perform the necessary
network namespace operations, specificall for the setns
call.
```
$ docker inspect  --format='{{.HostConfig.CapAdd}}' ecs-agent
[NET_ADMIN SYS_ADMIN]
```
> ecs-init/docker: start ECS Agent with CAP_SYS_ADMIN

- ecs-init/config/common.go
- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
Mount `/proc` 
**Description**
With task-enis, the ECS agent needs access to the container's
network namespace and for this; the agent needs access to the host procfs. This
patch mounts the host `/proc` as `/host/proc` within the agent container.
**Testing**
```
"HostConfig": {
"Binds": [
"/var/run:/var/run",
"/var/log/ecs:/log",
"/var/lib/ecs/data:/data",
"/etc/ecs:/etc/ecs",
"/var/cache/ecs:/var/cache/ecs",
"/proc:/host/proc"
],
"Mounts": [
….     
{
"Source": "/proc",
"Destination": "/host/proc",
"Mode": "",
"RW": true,
"Propagation": "rprivate"
},
….
],
```
> Mount /proc for agent

- scripts/lint.sh
Updated lint script ignore section to use new vendor folder. Enabled script due to increase in go version.
> Reenabled Lint script

- ecs-init/Godeps/Godeps.json
- ecs-init/config/common.go
- ecs-init/docker/dependencies.go
- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
- ecs-init/vendor/github.com/fsouza/go-dockerclient/.travis.yml
- ecs-init/vendor/github.com/fsouza/go-dockerclient/AUTHORS
- ecs-init/vendor/github.com/fsouza/go-dockerclient/README.markdown
- ecs-init/vendor/github.com/fsouza/go-dockerclient/appveyor.yml
- ecs-init/vendor/github.com/fsouza/go-dockerclient/client.go
- ecs-init/vendor/github.com/fsouza/go-dockerclient/client_unix.go
- ecs-init/vendor/github.com/fsouza/go-dockerclient/client_windows.go
- ecs-init/vendor/github.com/fsouza/go-dockerclient/container.go
- ecs-init/vendor/github.com/fsouza/go-dockerclient/event.go
- ecs-init/vendor/github.com/fsouza/go-dockerclient/exec.go
- ecs-init/vendor/github.com/fsouza/go-dockerclient/network.go
- ecs-init/vendor/github.com/fsouza/go-dockerclient/service.go
- packaging/amazon-linux-ami/ecs-init.spec
Changes required to start the Agent with Task ENI flag/feature enabled
* 555ca37 ecs-init/docker,packaging/amazon-linux-ami: start agent with --init
* 393b051 packaging/amazon-linux-ami: modify spec file with dhclient dependencies
* 7ccbab5 ecs-init/docker,ecs-init/config: modify agent create options to support task enis
> Start agent with task eni enabled flag

- ecs-init/docker/dependencies.go
- ecs-init/docker/dependencies_suse_ubuntu.go
- ecs-init/docker/dependencies_unspecified.go
- ecs-init/docker/docker.go
- ecs-init/docker/docker_suse_ubuntu.go
- ecs-init/docker/docker_unspecified.go
disable task eni feature on suse and ubuntu
Respect build flags when building Agent container config and host config to disable the Task ENI feature on suse and ubuntu platforms
> Disable task enis on suse/ubuntu

- ecs-init/docker/docker_test.go
- ecs-init/docker/docker_unspecified.go
- packaging/amazon-linux-ami/ecs-init.spec
Backs out most of the Task ENI changes in ECS Init for the ECS Agent. The only effective change is requiring docker version >= `17.03.2ce` and API client version `1.25` for amazon linux.
```
$ make clean test-in-docker rpm; echo $?
0
```
```
$ docker inspect ecs-agent --format '{{.HostConfig.Binds}}'
[/var/run:/var/run /var/log/ecs:/log /var/lib/ecs/data:/data /etc/ecs:/etc/ecs /var/cache/ecs:/var/cache/ecs]
```
```
$ docker inspect ecs-agent --format '{{.Config.Env}}'
[AWS_DEFAULT_REGION=us-west-2 ECS_DATADIR=/data ECS_UPDATES_ENABLED=true ECS_ENABLE_TASK_IAM_ROLE=true ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true ECS_UPDATE_DOWNLOAD_DIR=/var/cache/ecs ECS_LOGLEVEL=debug ECS_CLUSTER=aithal-eni ECS_LOGFILE=/log/ecs-agent.log ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","syslog","awslogs"] …
```
> Backout task eni changes

- ecs-init/docker/docker_test.go
- ecs-init/docker/docker_unspecified.go
- packaging/amazon-linux-ami/ecs-init.spec
This PR undoes the commit from #117 and re-enables the Task ENI changes
```
$ make clean test-in-docker rpm; echo $?
0
```
```
$ docker inspect ecs-agent --format '{{.HostConfig.Binds}}'
[/var/run:/var/run /var/log/ecs:/log /var/lib/ecs/data:/data /etc/ecs:/etc/ecs /var/cache/ecs:/var/cache/ecs /proc:/host/proc:ro /var/lib/ecs/dhclient:/var/lib/dhclient /lib64:/lib64:ro /sbin:/sbin:ro]
```
```
$ docker inspect ecs-agent --format '{{.Config.Env}}'
[ECS_CLUSTER=aithal-eni ECS_LOGFILE=/log/ecs-agent.log ECS_ENABLE_TASK_ENI=true ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","syslog","awslogs"] ECS_ENABLE_TASK_IAM_ROLE=true ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true ECS_AGENT_CONFIG_FILE_PATH=/etc/ecs/ecs.config.json ECS_UPDATE_DOWNLOAD_DIR=/var/cache/ecs ECS_LOGLEVEL=debug ECS_DATADIR=/data …
```
> reenable Task ENI changes for the Agent

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
This commit modifies the `ECS_AVAILABLE_LOGGING_DRIVERS` env var
for the Agent to include `none` logging driver. This compliments
https://github.com/aws/amazon-ecs-agent/pull/1041 PR in the
ECS Agent repository.
```
$ make clean test-in-docker rpm; echo $?
0
```
```
$ sudo start ecs
$ docker inspect ecs-agent -f '{{.Config.Env}}' | less
[... ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","syslog","awslogs","none"] ...]
$ aws ecs describe-container-instances --cluster $ECS_CLUSTER --container-instance $INSTANCE --query containerInstances[0].attributes[2]
{
"name": "com.amazonaws.ecs.capability.logging-driver.none"
}
```
```
- Add 'none' logging driver to ECS agent's config
```
> add 'none' logging driver to ECS Agent's config

- ecs-init/docker/docker_test.go
- ecs-init/docker/docker_unspecified.go
- packaging/amazon-linux-ami/ecs-init.spec
This change introduces a new `ECS_ENABLE_AWSLOGS_EXECUTIONROLE_OVERRIDE` environment variable to enable the corresponding agent feature. Also increment the required docker version to `17.06.2ce`. The docker version bump is required since it includes the awslogs credentials endpoint flag introduced here https://github.com/moby/moby/pull/35055
> add support for awslogs execution role

- ecs-init/docker/dependencies.go
- ecs-init/docker/dependencies_test.go
Handles scenarios where the docker socket isn't yet available.
I updated the condition in which the ping is retried.
Tests were modified to reflect the wrapped error and I tested this with a bad path to be sure.
New tests cover the changes:  yes
Fixed docker connection retry handling
> Handle wrapped error for docker connect retry

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
Mount Docker plugin files' directories in agent
Docker plugins socket, spec and json files are present in three different directories on the host. More details [here](https://docs.docker.com/engine/extend/plugin_api/#plugin-discovery). Mount these directories to agent to use it for volume plugins discovery. 
> mount Docker plugin files dir

- ecs-init/cache/cache.go
- ecs-init/cache/cache_test.go
- ecs-init/cache/dependencies.go
- ecs-init/cache/dependencies_mock_test.go
- ecs-init/config/common.go
- ecs-init/config/common_test.go
This pull request adds support for regional buckets.
The s3 downloader has two bucket downloaders internally, one corresponds to the partition bucket, another corresponds to the regional bucket. the download will succeed if either downloading from either bucket succeeds.
make test
Manual test is performed on the produced rpm.
yes
> Add support for regional buckets

- .gitignore
- Makefile
- ecs-init/ecs-init.go
- packaging/amazon-linux-ami/ecs-init.spec
- packaging/amazon-linux-ami/ecs.service
- scripts/amazon-ecs-init.1
- scripts/gobuild.sh
This change wraps the existing `ecs-init` daemon (with minor semantic modifications) with a systemd unit to run under Amazon Linux 2.
Minor modifications have been made to the entrypoints in the `ecs-init` binary to include the `stop` verb to align with systemd semantics surrounding service lifecycle. Though there is no difference from `post-stop` from upstart land, this allows the two to coexist in code if a change in handling is required at a later time.
The updated RPM spec accommodates both Amazon Linux and Amazon Linux 2 (thanks @ilianaw!) and includes a unit file suitable for running `ecs-init` on Amazon Linux 2 (with `systemctl start ecs`).
The RPM was built both for Amazon Linux and Amazon Linux 2 and run in an ECS Cluster with some tasks to confirm no functional differences were …
> Add ecs systemd unit for al2

- packaging/amazon-linux-ami/ecs.service
This change ensures `ecs.service` start after `cloud-final.service`, the last cloud-init stage ([see docs][0]), for user data configuration of ecs-init. There are transitive `Requires` and `Wants` from other dependent units (ie: though `docker.service`) that achieve a desired ordering however including `After=cloud-final.service` ensures dependent units' ordering do not change `ecs.service`'s order requirement.
10s delay is added between `amazon-ecs-init` restart attempts. This gives some back off time to restart `ecs-init` (eg: more than 100ms).
[0]: https://cloudinit.readthedocs.io/en/0.7.9/topics/boot.html
Appropriate systemd unit directives were added.
System starts up with dependencies in the correct order.
This contribution is under the terms of the …
> Improve ecs systemd unit

- ecs-init/config/common.go
- ecs-init/config/common_test.go
- packaging/amazon-linux-ami/ecs.service
This enables users to specify the environment variable `CGROUP_MOUNTPOINT` to direct `ecs-init` to use the provided path instead of the compiled default path.
Unit test is added and the service was used on an AL2 instance where a task's cgroup is setup.
The environment variable is consulted before falling back to the system's compiled in default path.
> Allow cgroup mountpoint to be specified by env variable

- ecs-init/config/common.go
- ecs-init/config/common_test.go
- ecs-init/config/config_al2.go
- packaging/amazon-linux-ami/ecs-init.spec
- packaging/amazon-linux-ami/ecs.service
The appropriate path is compiled into ecs-init for execution on Amazon
Linux 2 when targeted with the go build tag al2.
NB: This effectively undoes #176 to prefer compiled constants and obsoletes #177 
A `go build` tag was added to the respective config file with constants and updated the unspecified variants.
RPM builds completed successfully using the appropriate build tag passed to the build script. The unit starts up and sets up task cgroups on an Amazon Linux 2 instance without the environment variable previously present in the unit.
> Add al2 build tag and target in spec

- ecs-init/cache/dependencies.go
Added the attempted download URL to the Error logs when the download fails to allow engineers to more quickly determine the nature of the AccessDenied error.
Modified previous download failure message logging level from Debug to Error.
Added line in the downloadFile() method containing the attempted download URL log statement. 
Changed function in prior failure message from Debugf() to Errorf().
Ran 'make test'.
New tests cover the changes:  No new tests. 
Add the attempted download URL to ecs-init error logging.
> Add the attempted download URL to ecs-init error logging

- Makefile
Adds a hook target for preparing sources prior to the tarball being created.
An appendable `target-name::` allows additional target actions be appended as needed.
Confirmed target was called prior to `sources.tgz`.
> Add prepare-sources hook target

- ecs-init/config/common.go
- ecs-init/config/config_al2.go
- ecs-init/config/config_unspecified.go
- ecs-init/config/logger.go
- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
mounting root cert store director to agent container so cert store can be accessed by agent binary, additionally we're configuring the specific SSL_CERT_DIR to the paths expected on AL1 and AL2.
> config, docker: add host /etc/pki dir as mount

- ecs-init/config/common.go
- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
- ecs-init/engine/dependencies.go
- ecs-init/engine/dependencies_mocks.go
- ecs-init/engine/engine.go
- ecs-init/engine/engine_test.go
Custom GPU AMI configuration `ECS_ENABLE_GPU_SUPPORT` to be set at `/usr/lib/ecs/ecs.config` 
This will be further used for getting GPU information in the instance 
Note: This can be overridden by user config at `/etc/ecs/ecs.config`
> Consume custom instance configuration for GPU support

- scripts/gobuild.sh
address build error 
`go build github.com/aws/amazon-ecs-init/ecs-init/vendor/github.com/NVIDIA/gpu-monitoring-tools/bindings/go/nvml: invalid flag in #cgo LDFLAGS: -Wl,--unresolved-symbols=ignore-in-object-files`
> enable cgo for nvidia code

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
same as title
check if the instance config or env var `ECS_ENABLE_GPU_SUPPORT` is set to true and mount gpu info dir into agent container 
N/A
> mount gpu info dir only for GPU supported instances

- ecs-init/cache/cache.go
- ecs-init/cache/cache_test.go
- ecs-init/config/common.go
- ecs-init/config/common_test.go
- packaging/amazon-linux-ami/ecs-init.spec
This adds the necessary supporting packaging changes and code changes to support multiple architectures - arm64 specifically in this PR.
This PR should be merged prior to others as this contains the commit used for release of v1.22.0-4.
The downloader has been updated to pull the correct image from S3 and the packaging includes the appropriate image when built.
The v1.22.0-4 package was tested prior to its release.
- Add support for multiple architectures
> Add architecture support in v1.22.0-4 release

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
add GPU instance config variable `ECS_ENABLE_GPU_SUPPORT` to agent container only when GPU devices are present in the instance
Manual testing:
Non GPU instance:
```
$ docker inspect ecs-agent | grep "ECS_ENABLE_GPU_SUPPORT"
[ec2-user@ip-172-31-18-88 ~]$
```
GPU instance:
```
$ docker inspect ecs-agent | grep "ECS_ENABLE_GPU_SUPPORT"
"ECS_ENABLE_GPU_SUPPORT=true",
```
N/A
> send GPU instance config only when GPUs are present

- ecs-init/config/common.go
- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
- ecs-init/docker/docker_unspecified.go
- packaging/amazon-linux-ami/ecs-init.spec
https://github.com/aws/amazon-ecs-init/issues/209
This change removes the unused DHClient import and its references in ecs-init.
This was tested on a fresh ECS Optimized Amazon Linux EC2 instance; I ran unit tests against my changes using the make `gotest` target.
I changed docker_test.go to reflect the updated binds and bind count.
Feature - Remove the unused DHClient import and references
> remove references to DHClient

- ecs-init/gpu/nvidia_gpu_manager.go
When starting ecs-init, log Nvidia EULA Agreement before setting up Nvidia GPUs
> Log Nvidia EULA Agreement

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
- ecs-init/docker/docker_unspecified.go
Add binding /sbin, /usr/lib64, /lib64 to support iptable command for appmesh cni plugin
New tests cover the changes:  yes
> Add binding for agent container to be able to run iptables.

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
- ecs-init/docker/docker_unspecified.go
In order for iptables to execute, we also need /lib and /usr/lib to be mounted to the agent container.
If you have included new dependencies, please ensure you have followed
Packaging guidance from
https://github.com/aws/amazon-ecs-init/blob/master/CONTRIBUTING.md
-->
Manually tested on AL2 Arm a1.2xlarge
> Adding "/lib" and "/usr/lib" to the binds

- Makefile
- ecs-init/config/common.go
- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
Previously, the destination path of the docker socket bind mount is hardcoded to `/var/run/docker.sock`. However, when DOCKER_HOST is specified in `/etc/ecs/ecs.config`, the agent will ping the one specified here, which can be a value different from `unix:///var/run/docker.sock`. So, if customer is having a docker socket at a different path, they are not able to let the agent use it by specifying DOCKER_HOST. This mostly affects AL2 since on AL2 the values from `/etc/ecs/ecs.config` are also loaded as envs for ecs-init, while on AL1 the bind mount is normally just `/var/run:/var/run` (see comments above `getDockerSocketBind` for specific details).
This PR fixes this issue by specifying the destination path to match the one specified in `/etc/ecs/ecs.config` (if any).
Fixed the destination …
> Fix destination path in docker socket bind mount

- packaging/amazon-linux-ami/ecs-init.spec
Fix https://github.com/aws/amazon-ecs-init/issues/205. Drop unnecessary execution permission in some packaged files, including the one mentioned in the issue.
`install` sets file permission to `755` by default. Add `-m 644` to set file permisson to `644`.
Manually built the rpm and tested on both AL1 and AL2. Verified that the files have expected permission and the service can be started.
> Drop unnecessary execution permission in some packaged files

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
Fix https://github.com/aws/amazon-ecs-init/issues/227. The cause of the issue is that, on AL1, after the agent container stops, we don't try to stop it again (since it's in pre-stop), but on AL2, afterh the agent stops, we try to stop it again and fail (get a container not running error from Docker) since the pre-stop corresponds to the stop action of the systemd unit on AL2 (https://github.com/aws/amazon-ecs-init/blob/master/ecs-init/ecs-init.go#L101-L104). The failure causes the service to be restarted.
Fixing this behavior on AL2 by not failing the stop step when the agent container is not running.
Check stop container error from docker. if it's of type `ContainerNotRunning`, exits successfully.
Unit test added (combined all the unit tests for `(c *Client) StopAgent()` together). …
> Don't fail the service when stopping a stopped agent

- ecs-init/Gopkg.lock
- ecs-init/Gopkg.toml
- ecs-init/cache/dependencies_mocks.go
- ecs-init/docker/backoff_mocks.go
- ecs-init/docker/dependencies.go
- ecs-init/docker/dependencies_mocks.go
- ecs-init/docker/docker.go
- ecs-init/engine/dependencies.go
- ecs-init/engine/dependencies_mocks.go
- ecs-init/engine/engine.go
- ecs-init/engine/engine_test.go
- ecs-init/exec/iptables/cmd_mocks.go
- ecs-init/exec/iptables/exec_mocks.go
- ecs-init/exec/sysctl/cmd_mocks.go
- ecs-init/exec/sysctl/exec_mocks.go
- ecs-init/gpu/nvidia_gpu_manager_mocks.go
- ecs-init/vendor/github.com/golang/mock/gomock/call.go
- ecs-init/vendor/github.com/golang/mock/gomock/controller.go
- ecs-init/vendor/github.com/golang/mock/gomock/matchers.go
Author:    fierlion <fierlion@amazon.com>
Date:      Fri Dec 6 00:21:02 2019 +0000
Committer: fierlion <fierlion@amazon.com>
When the agent container fails, ecs-init removes the container as it starts up another.  We lose the failed container's logs.  This captures a set window of agent container logs and adds them to the ecs-init log for a failed container (exit code 2).
In order to avoid possibly searching through a large log, this uses the --tail flag of the docker Log and a pre-configured window (here set to 200 lines).  This assures us consistent performance.  I added a panic() to the agent container binary to force the agent container failed exit.  This returned a '2' exit code.  
We can tweak the window and potentially the exit code(s) we capture logs for over time as necessary.
I …
> capture a fixed tail of container logs when removing a container

- ecs-init/volumes/amazon-ecs-volume-plugin/plugin.go
- ecs-init/volumes/ecs_volume_driver.go
- ecs-init/volumes/ecs_volume_plugin.go
- ecs-init/volumes/ecs_volume_plugin_test.go
- ecs-init/volumes/state_manager.go
- ecs-init/volumes/state_manager_test.go
Amazon ECS Volume Plugin writes state information of the volumes
that it manages to `/var/lib/ecs/data/ecs_volume_plugin.json`. On
startup, it loads the volumes information from the disk and periodically
saves state on each volume's successful create and delete operations.
Tested manually.
state file after creating volume `efsVolume456` : 
```
$ sudo cat /var/lib/ecs/data/ecs_volume_plugin.json
{
"volumes": {
"efsVolume456": {
"type": "efs",
"path": "/var/lib/ecs/volumes/efsVolume456",
"options": {
"device": "fs-1cf5f8b7",
"o": "tls",
"type": "efs"
}
}
}
}
```
stopped the plugin and restarted 
```
$ docker volume ls
amazon-ecs-volume-plugin   efsVolume456
```
volume removal:
```
$ docker volume rm efsVolume456
$ sudo cat /var/lib/ecs/data/ecs_volume_plugin.json
{}
```
New tests cover the …
> store state information of the plugin to disk

- ecs-init/volumes/amazon-ecs-volume-plugin/plugin.go
- ecs-init/volumes/ecs_volume_driver.go
- ecs-init/volumes/ecs_volume_plugin.go
- ecs-init/volumes/efs_mount_helper.go
- ecs-init/volumes/logger/log.go
- ecs-init/volumes/logger/log_test.go
- ecs-init/volumes/state_manager.go
Using logfmt for seelog, and rollover based on date with roll count of 24 (mimicking agent's default logging behavior) 
Log file: `/var/log/ecs/ecs-volume-plugin.log`
Sample: 
```
level=info time=2020-01-13T20:16:20Z msg="Loading plugin state information"
level=info time=2020-01-13T20:16:20Z msg="starting volume plugin.."
level=info time=2020-01-13T20:16:27Z msg="Creating new volume efsvolume"
level=info time=2020-01-13T20:16:27Z msg="Creating mount target for new volume efsvolume"
level=info time=2020-01-13T20:16:27Z msg="Validating create options for volume efsvolume"
level=info time=2020-01-13T20:16:27Z msg="Mounting volume efsvolume at path /var/lib/ecs/volumes4/efsvolume with options tls"
level=info time=2020-01-13T20:16:27Z msg="Volume efsvolume created successfully"
level=info …
```
> Volume Plugin logging

- packaging/suse/amazon-ecs.service
This adds the appropriate stop, post-stop directives as requested here:
https://github.com/aws/amazon-ecs-init/issues/182
The `pre-stop` and `stop` actions point to the same `engine.PreStop` function
https://github.com/aws/amazon-ecs-init/blob/master/ecs-init/ecs-init.go#L97-L104
I updated the ExecStop to point to `stop` so it mirrors what we have in amazon-linux-ami
https://github.com/aws/amazon-ecs-init/blob/master/packaging/amazon-linux-ami/ecs.service#L29-L30
I also added the ExecStopPost directive.  
See testing for more detail.
1. Started a new EC2 instance from the `SUSE Linux Enterprise Server 15 SP1 (HVM), SSD Volume Type - ami-0e6612c7b620ecf3a` AMI in us-west-2.  
2. Set up Docker, provisioned host with necessary RPMs and then pulled the latest ECS-agent image from DockerHub. …
> Update suse systemd Unit file

- ecs-init/volumes/ecs_volume_plugin.go
- ecs-init/volumes/ecs_volume_plugin_test.go
- ecs-init/volumes/efs_mount_helper.go
Couple of things in this PR:
1. make "type" field in the volume creation request be non-mandatory. This allows bind mounts to be mounted using this volume plugin. 
tested bind mount with this: 
`docker volume create --name efsVolume0 -d amazon-ecs-volume-plugin --opt device=/var/lib/ecs/volumes/efsvolume1 --opt o=bind --opt target=/mnt`
2. When loading state from disk, the in-memory volumes list is updated, but not the structures used for actually storing the state. Changed that. 
Manually tested by stopping the plugin, creating a new volume and making sure the state file contains info of both the old and new volume. 
> allow no type for volume; populate volume state after load

- ecs-init/volumes/ecs_volume_plugin.go
- ecs-init/volumes/ecs_volume_plugin_test.go
- ecs-init/volumes/state_manager.go
To get information such as `createdAt` time, mount point for the volume, return it from the plugin. 
Testing:
```
$ docker volume inspect efsvolume0
[
{
"CreatedAt": "2020-01-17T21:33:38Z",
"Driver": "amazon-ecs-volume-plugin",
"Labels": {},
"Mountpoint": "/var/lib/ecs/volumes/efsvolume0",
"Name": "efsvolume0",
"Options": {
"device": "fs-1cf5f8b7",
"o": "tls,ro",
"type": "efs"
},
"Scope": "local"
}
]
```
State file:
```
$ sudo cat /var/lib/ecs/data/ecs_volume_plugin.json
{
"volumes": {
"efsvolume0": {
"type": "efs",
"path": "/var/lib/ecs/volumes/efsvolume0",
"options": {
"device": "fs-1cf5f8b7",
"o": "tls,ro",
"type": "efs"
},
"createdAt": "2020-01-17T21:33:38.172301878Z"
}
}
}
```
> return mount path and createdAt for get volume API

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
- ecs-init/docker/docker_unspecified.go
Fixes https://github.com/aws/amazon-ecs-init/issues/294. Newer version of Docker mounts tini to /sbin/init which conflicts our existing `/sbin:/sbin` mount. Updating the mount to `/sbin:/host/sbin`  fixes the problem. This needs to be accompanied by agent changes here - https://github.com/aws/amazon-ecs-agent/pull/2345.
Update the mount from `/sbin:/sbin` to `/sbin:/host/sbin`. I choose `/host/sbin` following the existing proc mount`/proc:/host/proc` as example. 
Unit test updated. The `/sbin` mount is only needed by the appmesh cni plugin to find the iptables binary, and our appmesh functional test will be ensuring the changes in init go out together with agent changes and don't break the appmesh feature. I've manually ran the test on an instance with Docker 19.03.5 and verifies that the …
> Update sbin mount point to avoid conflict with Docker

- Makefile
- packaging/amazon-linux-ami/amazon-ecs-volume-plugin.conf
- packaging/amazon-linux-ami/amazon-ecs-volume-plugin.service
- packaging/amazon-linux-ami/amazon-ecs-volume-plugin.socket
- packaging/amazon-linux-ami/ecs-init.spec
- scripts/gobuild.sh
This PR includes RPM packing and lifecycle management of ECS Volume plugin.
Modified ecs-init.spec file to support rpm packaging of ECS Volume Plugin
Added Systemd Unit file and Upstart configuration file to support lifecycle management of plugin on AL1 and AL2
Modified gobuild.sh to build Volume plugin
Tested Manually on AL1 and AL2. Successfully created volume using the ECS volume plugin.
> Packaging of Amazon ECS Volume Plugin

- CHANGELOG.md
- packaging/suse/amazon-ecs-init.changes
- scripts/changelog/CHANGELOG_MASTER
- scripts/changelog/README.md
- scripts/changelog/changelog.go
Currently we maintain multiple changelogs in ecs-init manually.  The release process makes updating the changelogs inconsistent. 
I'm seeking to make the process automatic. 
This creates a core changelog in the CHANGE_TEMPLATE file with all required details for each of the different changelog formats: amazon-linux/debian/markdown.
For each release, the engineer will update the CHANGE_TEMPLATE then will execute the changelog.go file (`go build changelog.go && ./changelog`)
Running the included script will update all the changelogs in place with the relevant contents of the CHANGE_TEMPLATE.
NOTE: All included new changelogs have been generated by the script.
Each or the entries in the CHANGE_TEMPLATE is parsed into a `Change` object.  An array of these change objects is passed to each of …
> Add script to generate/update changelogs

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
- ecs-init/volumes/ecs_volume_driver.go
- ecs-init/volumes/efs_mount_helper.go
- ecs-init/volumes/efs_mount_helper_test.go
This env var will be used by agent to send capability for EFS support by ECS Volume Plugin. 
Using the capability "efsAuth" and not "efs", since preview already supports "efs" capability , so to differentiate from that, we are using the "efsAuth" as the value. 
Added unit tests for efs_mount_helper.go , now that netns and creds uri options are finalized. 
> volume plugin capability for EFS and unit tests

- ecs-init/volumes/state_manager.go
Empty state files cannot be unmarshaled. 
Log that in volume plugin logs. 
testing: 
```
level=info time=2020-01-29T22:02:03Z msg="Loading plugin state information"
level=critical time=2020-01-29T22:02:03Z msg="Could not unmarshal existing state; corrupted data: unexpected end of JSON input. Please remove statefile at /var/lib/ecs/data/ecs_volume_plugin.json"
```
> handle state file corruption gracefully

- ecs-init/volumes/efs_mount_helper.go
Before the changes:
```
$ docker volume create --name efsvolume0  -d amazon-ecs-volume-plugin --opt o=tls,ro --opt type=efs --opt device=fs-3200b698
Error response from daemon: create efsvolume0: VolumeDriver.Create: mounting volume failed: exit status 32
```
After the changes:
```
$ docker volume create --name efsvolume0  -d amazon-ecs-volume-plugin --opt o=tls,ro --opt type=efs --opt device=fs-3200b698
Error response from daemon: create efsvolume0: VolumeDriver.Create: mounting volume failed: mount.nfs4: Connection reset by peer
```
> make mount/unmount commands return error string

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
- ecs-init/docker/docker_unspecified.go
In some circumstances, /sbin/iptables may be a symlink to a binary in
/etc/alternatives. In order to handle this case, its imperative that
agent is also able to access the /etc/alternatives folder.
We now mount in "/etc/alternatives" so that binaries within that directory are callable by agent.
**Testing is still WIP**
1. i build an rpm using `make rpm`
2. I installed it on an AL2 AMI
3. I've validated that the following appears upon docker inspect:
```
"Binds": [
"/var/run:/var/run",
"/var/log/ecs:/log",
"/var/lib/ecs/data:/data",
"/etc/ecs:/etc/ecs",
"/var/cache/ecs:/var/cache/ecs",
"/sys/fs/cgroup:/sys/fs/cgroup",
"/var/lib/ecs:/var/lib/ecs",
"/etc/pki:/etc/pki:ro",
"/run/docker/plugins:/run/docker/plugins:ro",
"/etc/docker/plugins:/etc/docker/plugins:ro", …
```
> docker: add '/etc/alternatives' to mounts

- packaging/amazon-linux-ami/ecs-init.spec
- packaging/suse/amazon-ecs-init.changes
- packaging/ubuntu-trusty/debian/changelog
- scripts/changelog/README.md
- scripts/changelog/changelog.go
Outputting the time format in local time is problematic because it will change based on the operator's current timezone. Even if they are in Seattle this can change depending on the time of the year (PDT/PST).
This PR changes the output timestamps for all of the changelogs to be in UTC.
> Changed changelog timestamp output to UTC

- ecs-init/volumes/efs_mount_helper.go
Lazy unmount efs volume. In case of awsvpc network mode, when we unmount the volume, task network namespace has been deleted and nfs server is no longer reachable, so umount will hang. Hence doing lazy unmount in the plugin.
Add "-f" flag for umount command.
Manually built rpm and tested with efs agent code [here](https://github.com/aws/amazon-ecs-agent/pull/2372). Verified that the volume can be cleaned up when doing lazy unmount, but cannot be cleaned up with unmount directly.
N/A
> Lazy unmount efs volume

- .travis.yml
- Makefile
- ecs-init/config/logger.go
- ecs-init/docker/dependencies_test.go
- ecs-init/docker/docker_suse_ubuntu.go
addresses https://github.com/aws/amazon-ecs-init/issues/298 
also fixes existing goimports errors 
adds gocyclo, goimports and govet target to travis 
mostly reused from https://github.com/aws/amazon-ecs-agent/blob/master/Makefile 
```
$ make static-check
gocyclo -over 15 /home/ec2-user/go/src/github.com/aws/amazon-ecs-init/ecs-init/ecs-init.go  /home/ec2-user/go/src/github.com/aws/amazon-ecs-init/ecs-init/backoff/backoff.go  /home/ec2-user/go/src/github.com/aws/amazon-ecs-init/ecs-init/cache/cache.go /home/ec2-user/go/src/github.com/aws/amazon-ecs-init/ecs-init/cache/dependencies.go /home/ec2-user/go/src/github.com/aws/amazon-ecs-init/ecs-init/cache/dependencies_mocks.go  /home/ec2-user/go/src/github.com/aws/amazon-ecs-init/ecs-init/cmd/cmd.go …
```
> add gocyclo, goimports target to travis

- ecs-init/volumes/ecs_volume_plugin.go
- ecs-init/volumes/ecs_volume_plugin_test.go
Currently, when mounting a volume failed for whatever reason, the mount path is left on the host. This PR adds the logic to cleanup the mount path in that case.
See above.
Modified existing unit test. Manually tested that with the fix mount path is cleaned up when mount failed.
New tests cover the changes:  yes
N/A
> Clean up mount path when mount failed

- ecs-init/volumes/ecs_volume_driver.go
- ecs-init/volumes/ecs_volume_driver_test.go
Remove volume from state when unmount failed with not mounted.
Currently when the plugin tries to unmount a volume that isn't mounted, it fails and the volume stays in the state forever. An example case that this can happen is to reboot the instance when an EFS task is running. The EFS volume is unmounted after reboot and the volume can't be removed.
Fixing by treating unmount failed with "not mounted" error as success and let the plugin remove the volume from state in that case.
See above.
Unit test added. Manually built rpm and tested that this fixed the issue.
New tests cover the changes:  yes
N/A
> Remove volume from state when unmount failed with not mounted

- packaging/amazon-linux-ami/ecs-init.spec
- packaging/ubuntu-trusty/debian/changelog
- scripts/changelog/CHANGELOG_MASTER
- scripts/changelog/changelog.go
RFC1123 seems to always parse the time in local time despite having a timezone in the timestamp, according to the go docs (https://golang.org/pkg/time):
> Note that the RFC822, RFC850, and RFC1123 formats should be applied only to local times. Applying them to UTC times will use "UTC" as the time zone abbreviation, while strictly speaking those RFCs require the use of "GMT" in that case. In general RFC1123Z should be used instead of RFC1123 for servers that insist on that format, and RFC3339 should be preferred for new protocols. RFC3339, RFC822, RFC822Z, RFC1123, and RFC1123Z are useful for formatting; when used with time.Parse they do not accept all the time formats permitted by the RFCs. The RFC3339Nano format removes trailing zeros from the seconds field and thus may not sort …
> Change CHANGELOG_MASTER to RFC3339 to fix UTC/Local issues

- packaging/suse/amazon-ecs-init.changes
- packaging/ubuntu-trusty/debian/changelog
- scripts/changelog/CHANGELOG_MASTER
This is a follow-up to https://github.com/aws/amazon-ecs-init/pull/320
The above PR was merged before the 1.38.0-1 release staging branch was merged. This fixes up the 1.38 CHANGELOG_MASTER entry to be inline with the new rfc3339 format.
> Fixup changelog from 1.38 release

- ecs-init/exec/sysctl/sysctl.go
- ecs-init/exec/sysctl/sysctl_test.go
This is a follow-up to #313
Some customers might have already disabled ipv6 entirely, which would
mean that the ipv6 accept_ra sysctl key wouldn't exist. In this case,
the sysctl command would fail and the agent would exit.
The -e flag tells sysctl not to fail if the config key doesnt exist.
from sysctl man page:
-e
Use this option to ignore errors about unknown keys.
> Use -e flag when disabling ipv6 router advertisements

- .travis.yml
- Makefile
- ecs-init/docker/docker.go
- scripts/changelog/changelog.go
Update Go version to 1.12.
Update static-check make target by adding staticcheck tool. Uses all default checks except code style check (-ST*).
Also fixes a golang inefficiency found by it.
static-check make target is updated with the command to run the check
Tested using the updated static-check make target
`make static-check`
> Update Go version, Add staticcheck, fix code inefficiencies found

- ecs-init/exec/iptables/iptables.go
- ecs-init/exec/iptables/iptables_test.go
Add iptable rule to drop traffic to 127.0.0.1 that isn't originated from the host. This is necessitated by the fact that we set `net.ipv4.conf.all.route_localnet` to 1.
Add following iptable rule when starting up:
```
iptables -I INPUT --dst 127.0.0.0/8 ! --src 127.0.0.0/8 -m conntrack ! --ctstate RELATED,ESTABLISHED,DNAT -j DROP
```
Remove the rule upon stop.
Some refactor in unit test code to reduce duplicate code and use assert/require from testify library.
Unit tests added/updated.
Built the rpm and verified that the expected iptable rule is added after the sevice start:
```
[ec2-user@ip-xxx ~]$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
DROP       all  -- !ip-127-0-0-0.us-west-2.compute.internal/8 …
```
> Drop traffic to 127.0.0.1 that isn't originated from the host

- README.md
- ecs-init/exec/iptables/iptables.go
- ecs-init/exec/iptables/iptables_test.go
Address https://github.com/aws/amazon-ecs-init/issues/336. Per https://github.com/aws/containers-roadmap/issues/976 for security purpose, an iptable rule is added to drop localhost traffic whose source address isn't in the localhost network and doesn't belong to an established connection/DNAT. As this can break some existing usage, adding a flag `ECS_SKIP_LOCALHOST_TRAFFIC_FILTER` to allow skipping local traffic filtering as a workaround.
On Amazon Linux 1, the flag can be turned on via adding `env ECS_SKIP_LOCALHOST_TRAFFIC_FILTER=true` to `/etc/init/ecs.conf`.
On Amazon Linux 2, the flag can be turned on via adding `ECS_SKIP_LOCALHOST_TRAFFIC_FILTER=true` to `/etc/ecs/ecs.config`.
Parse env ECS_SKIP_LOCALHOST_TRAFFIC_FILTER. If set to true, skip adding/removing the relevant iptable …
> Add a flag to allow skipping local traffic filtering

- README.md
- ecs-init/exec/iptables/iptables.go
- ecs-init/exec/iptables/iptables_test.go
Block offhost access to agent's introspection port by default.
During start, add iptable rule "iptables -A INPUT -i eth0 -p tcp --dport 51678 -j DROP". This blocks:
(b.1) offhost access from same subnet over instance private ip: http://$(instance_private_ip):51678;
(b.2) any access over instance public ip: http://$(instance_public_ip):51678;
(b.3) any access from container in awsvpc network mode over instance private ip: http://$(instance_public_ip):51678
This allows:
(a.1) on instance access over instance private ip: http://$(instance_private_ip):51678
(a.2) on instance access over localhost: http://localhost:51678
(a.3) same instance, from container in host network mode, over localhost and private ip: http://localhost:51678 and http://$(instance_private_ip):51678;
(a.4) same instance, …
> Block offhost access to agent's introspection port by default

- Makefile
`gocyclo` [changed](https://github.com/fzipp/gocyclo/commit/48b28985d52fd8113eb410d9bb09d17d977e7e9f) its `go get` path and this broke us. Changing it to fix the static check failures. 
Travis passes
> fixing gocyclo break

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
This is part of the change for ecs-agent to detect if an EC2 instance is `exec-enabled`, in other words, if the instance has the `exec` capability. Related change in [amazon-ecs-agent](https://github.com/aws/amazon-ecs-agent):
(add link to pr in ecs-agent)
Update ecs-init to add bind mounts to the ecs-agent containter for exec-for-ECS capability detection. For an EC2 instance to be considered as `exec-enabed`, the instance needs to have these resources required by SSM:
* SSM agent binaries
* ~~SSM agent configuration files~~ (not validated for now)
* certs files for SSM agent
For now, we only want to make sure all resources required by SSM (binaries, certs) exist. Since capabilities are stamped by ecs-agent, we need to provide a mechanism for the ecs-agent container to inspect the file …
> Add bind mount for agent

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
ECS Agent cleans up the exec agent logs when exec enabled tasks are cleaned up. 
In order for ECS agent to remove the logs, making them available through this bind mount. 
Note: Since this is done from init, check for 'exec capability' is not done before bind mounting the log path. 
bind mount `/var/log/ecs/exec` from host to `/log/exec` in agent container  
N/A
> add ExecAgent logs bind mount to agent

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
this change updates bind mounts to `ecs-agent` from `ecs-init` to use the constants defined in https://github.com/aws/amazon-ecs-agent/pull/2687.
update capability name to match the latest decision spec. add config folder as an a agent bind to allow ecs-agent to write (ssm configuration files) to host file system
manual test include starting the `ecs-agent` container and inspecting, automated unit test is also added
existing tests updated:
* TestStartAgentWithExecBinds
* TestGetCapabilityExecBinds
update capability ecs-exec name, add config to agent binds
> update capability name, add config to agent binds

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
change init to bind mount the certs folder instead of bind mount the specific cert file
Change from binding mount a specific file to binding mount a cert directory. 
Remove previous hostCertsFile and containerCertsFile.
Add new hostCertsDir and containerCertsDir. 
modify the existing tests
> Update bind mount for certs folder

- ecs-init/exec/iptables/iptables.go
- ecs-init/exec/iptables/iptables_test.go
This pull request fix https://github.com/aws/amazon-ecs-init/issues/360, 
Currently, iptables rule that drops packets to port 51678 is removed on ecs service stop only when ECS_ALLOW_OFFHOST_INTROSPECTION_ACCESS=false(default). When customer changing ECS_ALLOW_OFFHOST_INTROSPECTION_ACCESS from false to true with the consecutive systemctl restart ecs doesn't remove the iptables rule which drops packets to port 51678.
This PR remove iptables rule that drops packets to port 51678  unconditionally on ecs service stop to avoid the case above.
remove the conditional check, when customer change the ECS_ALLOW_OFFHOST_INTROSPECTION_ACCESS=False to True, stop/restart the iptable rule will be removed. 
modifies current test case. 
> remove iptables rule that drops packets to port 51678 unconditionally on ecs service stop.

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
add the logic bind mount the entire /host/dependency/path/execute-command/config folder
in read-write mode to allow ecs-agent to write config files to host file system 
docker will create the config folder if it does not exist
add the hostConfigDir bind mount unconditionally to add the case that if config dir when its not exists, we will create one.
> remove ifExists check for config folder

- ecs-init/Gopkg.toml
The version that was pulled in by `dep ensure` was actually 1.36.0 (the latest tagged version on that date). The version was originally malformed in the Gopkg.toml file.
I updated the Gopkg.toml file, ran `make get-dep` and `dep ensure` and there were no updates generated.
Ran `make gogenerate` then `make test` locally
Sync Gopkg.toml with Gopkg.lock
> sync aws-sdk-go version

- ecs-init/ecs-init.go
- ecs-init/engine/engine.go
- ecs-init/engine/engine_test.go
- packaging/amazon-linux-ami/ecs.service
Init is currently configured to restart on any failure. Today what happens is --
- Agent exits with code 5
- ecs-init, who monitors agent process status, received this error and kills itself with exit code -1.
- ecs-init restarts due to the restart policy 
- ecs-init restarts agent
Agent should not restart when it exits with exit code 5 as it is a terminal error code. This PR fixes this behavior. 
The behavior will be changed to --  
- Agent exits with code 5
- ecs-init, who monitors agent process status, received this error and kill itself with exit code 5.
- ecs-init does not restart as the restart policy is modified to not restart itself on exit code 5
Agent exiting with exit code 5 can be replicated by adding an arbitrary capability to ecs.config - 
``` …
```
> Prevent restart on exit code 5

- ecs-init/cache/cache.go
- ecs-init/cache/dependencies.go
- ecs-init/config/common.go
- ecs-init/config/common_test.go
- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
- ecs-init/docker/docker_unspecified.go
Add support for running in external (non-EC2) environment. This includes changes to:
1. Detect whether we are running in external env by checking env "ECS_EXTERNAL". When packing the ecs init rpm, ecs init will load an ecs.config file as an env file that sets this to true;
2. When detecting that we are running in external env, add the following behavior changes:
- Disable ec2 metadata call;
- Add host credentials bind mount;
- Disable task networking.
This pull request only make change to code but not packaging, just to allow the code to work with non-EC2 environment. Packaging changes will be added separately.
* `cache`: disable ec2 metadata call for agent tar downloader when running in external;
* `config`: add helper to detect whether we run in external env;  
* `docker`: add host …
> Add support for running in non-EC2 environment

- Makefile
- ecs-init/config/config_generic_rpm.go
- packaging/generic-rpm/amazon-ecs-init.spec
- packaging/generic-rpm/ecs.service
- packaging/suse/amazon-ecs-init.spec
Add generic rpm packaging (one that is not specific to platform). 
The changes include the following parts:
1. `packaging/generic-rpm/ecs-init.spec`: the rpm spec file used to built the rpm. This is written based on what we have on AL https://github.com/fenxiong/amazon-ecs-init/blob/master/packaging/amazon-linux-ami/ecs-init.spec, with the following notable differences:
* Remove all the AL1/upstart related logic and only use the AL2 part;
* Omit the distro part in https://github.com/aws/amazon-ecs-init/blob/master/packaging/amazon-linux-ami/ecs-init.spec#L36;
* Omit the docker dependency https://github.com/aws/amazon-ecs-init/blob/master/packaging/amazon-linux-ami/ecs-init.spec#L60. This is mainly because we have less control over docker outside of AL. it can come from "docker-ce", …
> Add generic rpm packaging

- Makefile
- ecs-init/config/config_generic_rpm.go
- ecs-init/config/config_unspecified.go
- packaging/generic-rpm/amazon-ecs-init.spec
Fix incorrect build tag. Build tag `generic-rpm` isn't valid due to containing dash, and then the build defaults to unspecified config. Changing to underscore `generic_rpm` to fix the issue.
Fix the build tag.
Built the rpm and verified that the agent cgroup mount is now correct (previously not)
```
{
"Type": "bind",
"Source": "/sys/fs/cgroup",
"Destination": "/sys/fs/cgroup",
"Mode": "",
"RW": true,
"Propagation": "rprivate"
},
```
and agent is able to create cgroup without error:
```
...
level=info time=2021-02-19T19:45:11Z msg="Creating root ecs cgroup: /ecs" module=init_linux.go
level=info time=2021-02-19T19:45:11Z msg="Creating cgroup /ecs" module=cgroup_controller_linux.go
level=info time=2021-02-19T19:45:11Z msg="Event stream ContainerChange start listening..." …
```
> Fix incorrect build tag

- Makefile
When we build a new version of ecs init package, the new agent version is available from file ecs-init/ECSVERSION, but not available from tag because the tag is created when we publish the release, but we build the package before that. This causes deb package build to use an agent version older than the release version.
Therefore, use the agent version from the ECSVERSION file instead of from `git describe --tags`.
Get agent version from `cat ecs-init/ECSVERSION` instead of from `git describe --tags`.
Built the deb package successfully. Verified that the version is read from file:
```
root@ip-172-31-12-102:/var/lib/ec2-stage/go/src/github.com/aws/amazon-ecs-init# make deb
./scripts/update-version.sh
++ dirname ./scripts/update-version.sh
+ CURRENTDIR=./scripts
++ cat …
```
> packaging/generic-deb: use agent version from file instead of tag

- packaging/generic-rpm/ecs.service
- scripts/ecs-anywhere-install-instruction.md
- scripts/ecs-anywhere-install.sh
* Removed ecs init rpm dependency on cloud-init.final: this is to allow the script to be ran in userdata (or by cloud-init in general);
* Fixed ssm agent install error on suse due to gpg signature: added `--no-gpg-checks` option when install. the ssm agent gpg signature is a detached signature and we verify explicitly before install.
* Added an optional flag --no-start: this is mainly for testing purpose so we can replace the agent being used for testing.
Described above.
Tested on ubuntu20, centos8 and opensuse15. Tested `--no-start` option working and ssm/docker/ecs agent can be started fine after the script with `sudo systemctl start amazon-ssm-agent` and `sudo systemctl start ecs`. Also checked that without `--no-start` the script still works fine.
N/A
This contribution is under the …
> A few fixes for ecs anywhere install

- scripts/ecs-anywhere-install.sh
Fix regional s3 endpoint suffix for cn region in install script. The endpoint suffix is "amazonaws.com.cn" instead of "amazonaws.com" for cn regions.
Fixing endpoint for all regional s3 endpoints used in the install script.
Tested e2e in cn region.
New tests cover the changes:  no
N/A
> Fix regional s3 endpoint suffix for cn region in install script

- scripts/ecs-anywhere-install.sh
Small fix in install script: check if dirmngr is installed before checking ecs init package signature. To import key with `gpg --key-server`, [dirmngr](https://www.gnupg.org/documentation/manuals/dirmngr/) needs to be installed. It is installed on most platforms by default but [might not be installed on debian](https://unix.stackexchange.com/questions/401547/gpg-keyserver-receive-failed-no-dirmngr)
Fix by checking dirmngr installed or not before verifying signature.
Tessted on all ecs anywhere platforms. Fixed error on debian.
N/A
> install script: check if dirmngr is installed before checking signature

- scripts/ecs-anywhere-install.sh
Ensure the temporary directories into which package artifacts are downloaded are world-readable, thereby allowing the unprivileged `_apt` user to open the packages and allow for a sandboxed install.
This fix eliminates warnings such as:
```
N: Download is performed unsandboxed as root as file '/tmp/tmp.ZkW0dDLEph/amazon-ecs-init-latest.amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
```
> ecs-anywhere-install: allow sandboxed apt installations

- scripts/ecs-anywhere-install.sh
Fix rpm/deb download url for cn region, previously incorrect; also update link of the ssm/ecs agent public key to more official location.
Fix the url; update links.
Tested manually on ubuntu and centos for cn region. Also ran through the e2e tests for cn and some other regions.
ecs-anywhere-install: fix incorrect download url when running in cn region.
> Fix download url for cn region

- .github/workflows/build.yml
- Makefile
Added github action to replace previous travis-ci check (which is no longer available to use). This is based on https://github.com/aws/amazon-ecs-init/pull/356 with a small fix.
Added github action. Fixed `get-deps` make target which was failing due to a known issue in gocyclo (see https://github.com/aws/amazon-ecs-agent/pull/2959).
Tested in pr check.
N/A
> Adding github action check

- scripts/ecs-anywhere-install.sh
This pr makes changes to the ECS Anywhere installation script in order for exec to be supported on ECS Anywhere. Two changes are required - copying TLS certs and downloading ssm binaries. Both of these will be moved to a directory that will be bind-mounted into the customer's container at start, which is consistent with the current behavior for ECS exec on EC2.
For further context on exec, see:
- [Original ECS Exec proposal](https://github.com/aws/containers-roadmap/issues/1050)
- [AWS Docs on using ECS Exec](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-exec.html#ecs-exec-required-iam-permissions)
- [ECS Exec blog post](https://aws.amazon.com/blogs/containers/new-using-amazon-ecs-exec-access-your-containers-fargate-ec2/)
The changes to installation script are:
1. Move …
> add exec prerequisites to ecs-anywhere installation script

- scripts/ecs-anywhere-install.sh
This PR updates the ECS-A installation script to make it work on AL2. It makes following changes to the script:
* Enables detection of AL2 OS and set the DISTRO variable in the script accordingly when running on AL2 instances
* Using the set DISTRO variable, bypass the 'yum install epel-release -y' command (if we don't, we get error here). This command is required for supporting Centos 7 for enabling installation of required packages (jq, docker). For AL2, these are enabled by default and not required
* Launched a non ECS optimized AL2 instance and tested by running the script to join an ECS cluster as an external instance. Then ran a simple task on it and verified the exit code is as required for a successful task completion. Also checked userdata log to verify package installation
This …
> Enable AL2 support for ECS-A

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
- ecs-init/engine/engine.go
- ecs-init/engine/engine_test.go
Initialize docker client lazily. This will help mitigate the issues observed in https://github.com/aws/amazon-ecs-init/issues/448
Initializing docker client lazily when `docker.Client` is invoked. 
In order to mock docker client in UTs, `docker.Client` is aliased by means of package-level variable. This variable is overridden in UTs with a function that returns a mocked docker client.
No drastic changes in logic are introduced with this change, but merely the way in which the docker client is wired.
UTs passing, built ecs-init binary and verified it is still able to start and stop the ecs-agent.
* Enhancement - Initialize docker client lazily 
> Initialize docker client lazily

- scripts/ecs-anywhere-install.sh
If $NO_START variable is true, the script should not start the ssm agent. But current behavior is that it will fall through the if else clause and the ```systemctl start "$SSM_SERVICE_NAME"``` is executed irrespective of the variable. Note that it is executed twice if the variable is set to false. This change fixes it by removing the second unrequired command.
Tested by verifying instances are getting connected to cluster for centos 7 and AL2, and change goes through CI tests
> ECS-A script remove unrequired start ssm-agent

- scripts/ecs-anywhere-install.sh
Since we are allowing customers to provide a cert, verify the cert with `openssl verify`.
Ran install script with an empty file, a self-signed TLS cert, and a copied valid cert. Script failed on first two and succeeded on next. Verified that, without this check, the ssm agent in task containers would also have issues in the first two cases and succeed on the latter.
> add verification to cert for exec support in ecs-a installation script

- packaging/generic-deb/debian/README.source
- packaging/generic-deb/debian/amazon-ecs-init.install
- packaging/generic-deb/debian/amazon-ecs-volume-plugin.service
- packaging/generic-deb/debian/amazon-ecs-volume-plugin.socket
- packaging/generic-deb/debian/rules
This PR ensures `make deb` includes amazon-ecs-volume-plugin binary and startup scripts in the resulting Debian package
Fixes https://github.com/aws/amazon-ecs-init/issues/431
Modify Debian build scripts.
Built on Ubuntu 18.04 Bionic and tested to work.
New tests cover the changes:
No automated tests, but we are running Ubuntu in our environment, and I copied the existing amazon-ecs-volume-plugin.service and amazon-ecs-volume-plugin.socket systemctl configuration files into the generic-deb directories and ensured the amazon-ecs-volume-plugin binary is included in the resulting package. I checked that all required files are included in the generated .deb packaged by running dpkg -c <package>, then installed the package, and mounted an EFS file system that requires IAM permissions and …
> Include amazon-ecs-volume-plugin and startup scripts in Debian Package

- scripts/ecs-anywhere-install.sh
fixes https://github.com/aws/amazon-ecs-init/issues/446. due to reason mentioned in the issue, dirmngr is not necessary in order to check the package signature, so can be removed.
removed check on dirmngr.
tested the script on a debian image without dirmngr. script runs successfully including signature check.
New tests cover the changes:  N/A
* ecs-anywhere-install: remove check on dirmngr
> install script: remove check on dirmngr

- Makefile
- packaging/generic-rpm/README.md
- packaging/generic-rpm/amazon-ecs-init.spec
- packaging/generic-rpm/amazon-ecs-volume-plugin.service
- packaging/generic-rpm/amazon-ecs-volume-plugin.socket
Add `amazon-ecs-volume-plugin` to `generic-rpm` package
Mostly the same as https://github.com/aws/amazon-ecs-init/pull/433. Fixed some minor issue, added readme and did some tests.
New tests cover the changes:  N/A
* MACIS ecs-a tests passed with .rpm package built by code change
* Install package on a fedora34 instance and successfully run a task with EFS in task definintion.
This contribution is under the terms of the Apache 2.0 License: 
yes
> add amazon-ecs-volume-plugin to rpm generic package

- scripts/ecs-anywhere-install.sh
Downgrading the ssm version for exec to be consistent with the one used in our [amis for EC2](https://github.com/aws/amazon-ecs-ami/blob/main/variables.pkr.hcl#L59). 
Testing included
- ran tasks with the `start-task` and `run-task` apis and exec'd into the tasks
- create a service with the execute command enabled and exec'd into a task started by the service
- verified that logging to cloudwatch and s3 still worked
- verified that encrypting data with KMS still worked
- curl'd for the binary file in a few regions (us-west-2, cn-north-1, eu-west-1, ap-south-1)
downgrade ssm binary version for exec
> downgrade ssm binary version for exec

- Makefile
- README.md
- scripts/dockerfiles/build.dockerfile
This lets us use the command `make rpm-in-docker` to build locally. This
is a good approximation of an authorative build that we can use to test
changes to init.
```
make rpm-in-docker
```
This is currently hardcoded to al2 -- but we can amend it in the future to include an option to build the generic rpm as well.
> build al2 rpm in docker

- Makefile
- packaging/generic-deb/debian/README.source
- packaging/generic-deb/debian/amazon-ecs-init.install
- packaging/generic-deb/debian/amazon-ecs-volume-plugin.service
- packaging/generic-deb/debian/amazon-ecs-volume-plugin.socket
- packaging/generic-deb/debian/rules
- packaging/generic-rpm/README.md
- packaging/generic-rpm/amazon-ecs-init.spec
- packaging/generic-rpm/amazon-ecs-volume-plugin.service
- packaging/generic-rpm/amazon-ecs-volume-plugin.socket
This PR cherry-picks the previous volume plugin updates commits, and remove the curl line which breaks during release init build, also updates the readme for customized rpm build
See previous PRs https://github.com/aws/amazon-ecs-init/pull/450 and https://github.com/aws/amazon-ecs-init/pull/462
New tests cover the changes:  N/A
Tests done for pr #450 and #462 :
1. Build ecs-init locally
2. Upload ecs-init to S3
3. Update install script to use above ecs-init
4. Use updated install script to run MACIS ECS anywhere tests
Tests done for fixing the release build failure: test build in shadow stage pipeline
> Add volume to rpm/deb package

- packaging/amazon-linux-ami/ecs-init.spec
- scripts/gobuild.sh
This PR updates `packaging/amazon-linux-ami/ecs-init.spec` and `scripts/gobuild.sh` for packing ecs-init rpm for [Amazon Linux 2022 (AL220)](https://aws.amazon.com/linux/amazon-linux-2022/faqs/) OS.
1. Add `%global debug_package %{nil}` in amazon-linux-ami/ecs-init.spec to fix `RPM build errors: Empty %files file...`.
2. Append an argument `ecs` after %systemd_postun` in amazon-linux-ami/ecs-init.spec to fix `error: The %systemd_postun macro requires some arguments`.
3. Set `GO111MODULE="auto"` in  gobuild.sh to only use go modules if modules exist.
1. Built ecs-init rpm on an AL2022 instance (x86_64 and aarch64), installed ECS Agent version 1.58 from the rpm, and ran ECS tasks successfully.
2. Built ecs-init rpm in an AL1 and AL2 (x86_64 and aarch64) using Koji, installed ECS Agent …
> [AL2022] Set GO111MODULE=auto and update ecs-init.spec

- scripts/ecs-anywhere-install.sh
This PR removes the hardcoded amazon-ssm-agent fingerprint validation from ecs-anywhere-install.sh.
We're maintaining GPG verification of the SSM agent rpm. The signature of amazon-ssm-agent rpm has been verified before installation as below.
```
if gpg --verify "$1" "$2"; then
echo "amazon-ssm-agent GPG verification passed. Install the amazon-ssm-agent."
else
echo "amazon-ssm-agent GPG verification failed. Stop the installation of the amazon-ssm-agent. Please contact AWS Support."
fail
fi
```
Lines for the hardcoded amazon-ssm-agent fingerprint validation are removed from ecs-anywhere-install.sh.
Tested on ubuntu amd64 in us-west-2
* Launch an EC2 instance (AMI name: ubuntu-minimal/images/hvm-ssd/ubuntu-focal-20.04-amd64-minimal-20220308)
* ssh into the instance and uninstall …
> Remove the hardcoded amazon-ssm-agent fingerprint validation from ecs-anywhere-install.sh

- Makefile
Add `GO111MODULE=on` to honnef.co/go/tools/cmd/staticcheck to make `make get-deps` happy in the PR CI build checks. Sample PR where this check failed - https://github.com/aws/amazon-ecs-init/pull/503
Identical to https://github.com/aws/amazon-ecs-agent/pull/3193
> Add GO111MODULE=on to honnef.co/go/tools/cmd/staticcheck

- scripts/ecs-anywhere-install.sh
ECS now supports cgroups v2 and no longer needs to block the install in this case.
Reference:
https://github.com/aws/containers-roadmap/issues/1535
https://github.com/aws/amazon-ecs-agent/pull/3127
I removed the flow logic that bails if it detects cgroups v2.
I have been able to successfully run the install script and get a properly running ECS agent in docker on a cgroups v2 debian bullseye docker container.
Bug - Install script no longer fails on systems using cgroups v2
> ECS now supports cgroups v2

- ecs-init/docker/docker.go
- ecs-init/docker/docker_config.go
- ecs-init/docker/docker_test.go
EcsInit needs to be able to change the ownership of files/directories for ServiceConnect and potentially existing features as well. This ensures it can do that even if running rootless.
Add CAP_CHOWN to list of privileged capabilities.
> Add the CAP_CHOWN capability to support running rootless

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
This results in the same set of folders available for ExecCommand support
but also includes as RO the whole /var/lib/ecs/deps/ tree for additional
features such as ServiceConnect to reuse without adding additional mounts.
> Extend the mounting to include all dependencies
