aws/amazon-ecs-init

- Makefile
- ecs-init.spec
- ecs-init/cache/cache.go
- ecs-init/cache/cache_test.go
- ecs-init/cache/dependencies.go
- ecs-init/cache/dependencies_mock_test.go
- ecs-init/config/common.go
- ecs-init/config/development.go
- ecs-init/config/logger.go
- ecs-init/config/release.go
- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
- ecs-init/ecs-init.go
- ecs-init/engine/dependencies.go
- ecs-init/engine/dependencies_mock_test.go
- ecs-init/engine/engine.go
- ecs-init/engine/engine_test.go
- scripts/bundle_log_config.sh
- scripts/dockerfiles/exit-success.dockerfile
- scripts/dockerfiles/mock-agent.dockerfile
- scripts/dockerfiles/wants-update.dockerfile
- scripts/mock-ecs-agent.sh
@euank, @dangrd, @aaithal: Care to take a look?
> Enable Agent updates and bump version to 1.0-1

- .travis.yml
- Makefile
- scripts/dockerfiles/test.dockerfile
- scripts/hack/symlink-gopath-travisci
- scripts/test
Successful build in Travis CI: https://travis-ci.org/samuelkarp/amazon-ecs-init/builds/58673119
r? @euank @aaithal
> Add Travis CI and test-in-docker for tests

- packaging/amazon-linux-ami/ecs-init.spec
- scripts/amazon-ecs-init.1
> Add man page for amazon-ecs-init

- ecs-init/cache/cache.go
- ecs-init/cache/cache_test.go
- ecs-init/cache/dependencies.go
- ecs-init/cache/dependencies_mock_test.go
- ecs-init/config/common.go
- ecs-init/engine/dependencies.go
- ecs-init/engine/dependencies_mock_test.go
- ecs-init/engine/engine.go
- ecs-init/engine/engine_test.go
- packaging/amazon-linux-ami/ecs-init.spec
> On upgrade, always update cache and reload

- packaging/amazon-linux-ami/ecs-init.spec
Just support for Docker 1.6.2 with no other changes.
r? @euank
> Add support for Docker 1.6.2

- ecs-init/config/common.go
- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
- packaging/amazon-linux-ami/ecs-init.spec
I have not actually tested this yet but wanted to get the change out for review earlier rather than later.
r? @euank @aaithal
> Update to support Agent 1.2.0 with Telemetry

- ecs-init/config/common.go
- packaging/amazon-linux-ami/ecs-init.spec
> Update to support Agent 1.3.0

- ecs-init/config/common.go
- ecs-init/config/common_test.go
- ecs-init/docker/dependencies.go
- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
Superseding https://github.com/aws/amazon-ecs-init/pull/15 to merge on top of dev. Also, squashed all commits and added unit tests as requested by @samuelkarp
> Read docker endpoint from environment varibale DOCKER_HOST if present.

- ecs-init/config/common.go
- packaging/amazon-linux-ami/ecs-init.spec
> Update to support Agent 1.4.0

- packaging/amazon-linux-ami/ecs-init.spec
> Add support for Docker 1.7.1

- ecs-init/config/common.go
- packaging/amazon-linux-ami/ecs-init.spec
> Update to support Agent 1.7.0

- ecs-init/config/common.go
- packaging/amazon-linux-ami/ecs-init.spec
- Cache Agent version 1.7.1
r? @aaithal @euank @juanrhenals
> Update to support Agent 1.7.1

- ecs-init/config/common.go
- packaging/amazon-linux-ami/ecs-init.spec
* Cache Agent version 1.8.1 
r? @aaithal @samuelkarp
> Update to support Agent 1.8.1

- ecs-init/config/common.go
- packaging/amazon-linux-ami/ecs-init.spec
* Cache Agent version 1.8.2
r? @aaithal @samuelkarp
> Update to support Agent 1.8.2

- Makefile
- scripts/lint.sh
> Disable golint, fix goimports dependency

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
> Make `awslogs` driver available by default

- Makefile
- ecs-init/config/common.go
- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
- packaging/amazon-linux-ami/ecs-init.spec
- scripts/lint.sh
@samuelkarp @aaithal @juanrhenals
> Update to support Agent 1.9.0

- .travis.yml
- ecs-init/config/common.go
- packaging/amazon-linux-ami/ecs-init.spec
r? @aaithal @richardpen @juanrhenals
> Update to support Agent 1.11.1

- .gitignore
- ecs-init/config/common.go
- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
- ecs-init/exec/iptables/iptables.go
- ecs-init/exec/iptables/iptables_test.go
- packaging/amazon-linux-ami/ecs-init.spec
* Enable Task IAM Role for containers launched with 'host' network mode
* Change log for 1.12.0
Closed #55 and created the PR with a branch named `stage`.
r? @samuelkarp @richardpen @juanrhenals
> Update to support Agent 1.12.0

- ecs-init/config/common.go
- packaging/amazon-linux-ami/ecs-init.spec
Cache Agent 1.12.1
r? @samuelkarp @aaithal  @juanrhenals
> Update to support Agent 1.12.1

- ecs-init/config/common.go
- packaging/amazon-linux-ami/ecs-init.spec
Cache Agent 1.12.2
r? @samuelkarp @richardpen
> Update to support Agent 1.12.2

- ecs-init/Godeps/Godeps.json
- ecs-init/config/common.go
- ecs-init/docker/dependencies.go
- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
- ecs-init/vendor/github.com/fsouza/go-dockerclient/.travis.yml
- ecs-init/vendor/github.com/fsouza/go-dockerclient/AUTHORS
- ecs-init/vendor/github.com/fsouza/go-dockerclient/README.markdown
- ecs-init/vendor/github.com/fsouza/go-dockerclient/appveyor.yml
- ecs-init/vendor/github.com/fsouza/go-dockerclient/client.go
- ecs-init/vendor/github.com/fsouza/go-dockerclient/client_unix.go
- ecs-init/vendor/github.com/fsouza/go-dockerclient/client_windows.go
- ecs-init/vendor/github.com/fsouza/go-dockerclient/container.go
- ecs-init/vendor/github.com/fsouza/go-dockerclient/event.go
- ecs-init/vendor/github.com/fsouza/go-dockerclient/exec.go
- ecs-init/vendor/github.com/fsouza/go-dockerclient/network.go
- ecs-init/vendor/github.com/fsouza/go-dockerclient/service.go
- packaging/amazon-linux-ami/ecs-init.spec
> Merge enis to dev 09052017

- ecs-init/engine/engine.go
Hello folks,
Just correcting an annoying typo here, nothing too onerous.
> Correct typo Serivce > Service

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Merge github issue and pull request template files from master to dev.
Add two files that were already merged to master. Not sure how I got this
wrong in the original commit. Obviously, the change should have gone into
dev first and master second!
N/A
> Merge github issue and pull request template files to dev branch (they should have been there before master anyway)

- ecs-init/config/common.go
This PR adds an S3 bucket for the AWS GovCloud reigon.
This contribution is under the terms of the Apache 2.0 License:   yes
> Add GovCloud agent bucket path.

- ecs-init/config/common.go
- packaging/amazon-linux-ami/ecs-init.spec
- packaging/ubuntu-trusty/debian/changelog
> Cache agent 1.17.1.

- ecs-init/config/common.go
- packaging/amazon-linux-ami/ecs-init.spec
- packaging/ubuntu-trusty/debian/changelog
> Update to Agent 1.17.2

- scripts/gobuild.sh
- scripts/update-version.sh
Enforce 8 character Git short SHAs.
> Enforce 8 character git short sha

- ecs-init/cache/cache.go
- ecs-init/config/common.go
- ecs-init/config/common_test.go
make test
yes
This contribution is under the terms of the Apache 2.0 License: 
yes
> Download the agent based on partition

- .gitignore
- Makefile
- ecs-init/ecs-init.go
- packaging/amazon-linux-ami/ecs-init.spec
- packaging/amazon-linux-ami/ecs.service
- scripts/amazon-ecs-init.1
- scripts/gobuild.sh
This change was inadvertently merged directly into the master and needs to be restaged for inclusion for release out of dev.
This reverts commit 52d57923b3637b7cb140c409f78e3e00226b2d67 and includes the intended changes from #171 
> Add ecs-init-unit from #171

- .travis.yml
- ecs-init/config/common.go
- ecs-init/config/config_al2.go
- ecs-init/config/config_suse_ubuntu.go
- ecs-init/config/config_unspecified.go
- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
add host SSL cert directory path for AL and AL2
added expected paths to platform specific config files behind build flags.
> config, docker: config certs dir path

- ecs-init/config/common.go
- ecs-init/config/config_suse_ubuntu.go
addresses https://github.com/aws/amazon-ecs-init/pull/199#discussion_r224167578
> config: add hostPKIDirPath for ubuntu, suse

- ecs-init/Gopkg.lock
run dep ensure for v0.5.0 
`dep ensure`
> run dep ensure on dev

- packaging/amazon-linux-ami/ecs-init.spec
> Bump release to 3 for rebuild

- ecs-init/gpu/nvidia_gpu_manager.go
> remove nvidia docker version field

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
`ECS_ENABLE_GPU_SUPPORT=true` is now present in all instance types. 
as a result of this, `/var/lib/ecs/gpu` folder is bind mounted to agent container on non p2,p3 instances. 
Hence, check for presence of GPUs in the instances and then bind mount / create the gpu folder. 
Manual testing (after the fix)
Agent container is inspected for any bind mounts of the folder `/var/lib/ecs`
On a m4.2xl instance: 
```
ECS_ENABLE_GPU_SUPPORT=true
2018-12-22T01:20:44Z [INFO] pre-start
ls: cannot access /var/lib/ecs/gpu: No such file or directory
2018-12-22T01:34:19Z [INFO] start
$ docker inspect 9e2af4ee7869 | grep /var/lib/ecs/gpu
[ec2-user@ip-172-31-18-88 ~]$ *no results*
```
On a p3.2xl instance: 
```
2018-12-22T01:25:44Z [INFO] pre-start
{
"DriverVersion": "396.26",
"GPUIDs": [ …
```
> bind mount GPU folder only when devices are present

- ecs-init/engine/engine.go
> gpu: more logging

- packaging/amazon-linux-ami/ecs.service
- packaging/suse/amazon-ecs.service
Update systemd unit description and add documentation url.
Directives were updated in the systemd units.
I dropped the changed unit into `/etc/systemd/system` and ran the following:
```yaml
● ecs.service - Amazon Elastic Container Service - container agent
Loaded: loaded (/etc/systemd/system/ecs.service; disabled; vendor preset: enabled)
Active: inactive (dead)
Docs: https://aws.amazon.com/documentation/ecs/
```
> Update systemd unit description and add url

- ecs-init/engine/engine.go
Because we hide the service's return code from systemd/sysV/upstart, we are not able to use the init system's builtin restart limiting.
With this change we can backoff restarting the service to avoid a situation where the service continuously restarts many times per second, resulting in numerous API calls to startup APIs with zero backoff, as each time the service starts it would be with a "fresh" API backoff counter.
> service start: add backoff to service restarts

- README.md
Update documentation for https://github.com/aws/amazon-ecs-init/pull/260.
> Document ECS_AGENT_LABELS usage

- Makefile
- ecs-init/engine/engine.go
- scripts/test
This adds `go vet` as a Makefile target.  It also fixes the one generated warning from running go vet.
```
$ go vet ./...
ecs-init/engine/engine.go:219: unreachable code
```
I added `go vet` with a shell list command to be in sync with amazon-ecs-agent's go vet make target.  This might be useful at some point if we decide to vet a specific subset of directories.
I added the new govet target to the test targets.  
I tested in place on a fresh ECS-optimized AL2 EC2 instance.  
```
$ make clean
rm -f ecs-init.spec
rm -f ecs.conf
rm -f ecs.service
rm -f ./sources.tgz
rm -f ./amazon-ecs-init
rm -f ./ecs-agent-*.tar
rm -f ./ecs-init-*.src.rpm
rm -rf ./ecs-init-*
rm -rf ./BUILDROOT BUILD RPMS SRPMS SOURCES SPECS
rm -rf ./x86_64
rm -f ./amazon-ecs-init_1.35.0*
rm -f .srpm-done .rpm-done
$ make …
```
> add go vet to makefile

- .gitignore
- ecs-init/Gopkg.lock
- ecs-init/backoff/backoff_test.go
- ecs-init/cache/cache_test.go
- ecs-init/docker/dependencies_test.go
- ecs-init/docker/docker_test.go
- ecs-init/vendor/github.com/stretchr/testify/require/doc.go
- ecs-init/vendor/github.com/stretchr/testify/require/forward_requirements.go
- ecs-init/vendor/github.com/stretchr/testify/require/require.go
- ecs-init/vendor/github.com/stretchr/testify/require/require.go.tmpl
- ecs-init/vendor/github.com/stretchr/testify/require/require_forward.go
- ecs-init/vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
- ecs-init/vendor/github.com/stretchr/testify/require/requirements.go
This PR updates some unit tests to use the `github.com/stretchr/testify` package as requested in this issue: https://github.com/aws/amazon-ecs-init/issues/98
`make gotest` runs successfully 
no additional tests added 
Enhancement - update some ecs-init unit tests to use the testify package 
> update unit tests to use testify package

- ecs-init/volumes/ecs_volume_plugin.go
- ecs-init/volumes/ecs_volume_plugin_test.go
Earlier, target field was ignored for volume creation and mount. Now if target path is specified, the volume is mounted at that location. 
> accept target field for volume creation

- ecs-init/volumes/ecs_volume_plugin.go
- ecs-init/volumes/ecs_volume_plugin_test.go
In the current code, after successfully creating/mounting/removing volumes, if saving the volume info to disk fails, we return an error to Docker. This is not correct, since the volumes are actually successfully created/removed. 
The state will be saved to disk again during the next create/remove call. 
> not failing create/remove calls if save state to disk fails

- scripts/changelog/changelog.go
Adds validation of the master changelog:
Datetimes are all in ascending order
No duplicate versions found
Also, I ran `gofmt`.
The only real change is the addition of the new validateChangelog() function.
Tested manually with multiple variations of changelog
Add validation to changelog generation
> add validation of master changelog

- ecs-init/volumes/ecs_volume_driver.go
removed unnecessary logging of mount options. 
> not logging volume  mount options

- ecs-init/engine/dependencies.go
- ecs-init/engine/dependencies_mocks.go
- ecs-init/engine/engine.go
- ecs-init/engine/engine_test.go
- ecs-init/exec/sysctl/sysctl.go
- ecs-init/exec/sysctl/sysctl_test.go
optimization: disable ipv6 router advertisements
> optimization: disable ipv6 router advertisements

- Makefile
- README.md
gocyclo and mockgen are needed for running tests and generating mocks, so add them to the makefile
also add a blurb about getting dependencies and generating mocks in the README
> Update makefile and readme

- ecs-init/config/common.go
- ecs-init/config/common_test.go
Adds environment variables ECS_LOG_DRIVER and ECS_LOG_OPTS to allow a logging driver to be set for the Agent container when using ecs-init.
Changes how the godocker LogConfig is set by overriding the defaults with the values from the environment variables, if they are set. The option to set max-size and max-file for the json-file logging driver with ECS_INIT_DOCKER_LOG_FILE_SIZE and ECS_INIT_DOCKER_LOG_FILE_NUM still exists, but those values will be overridden if ECS_LOG_OPTS is set. 
Unit tests for testing the configuration, will also do smoke test.
> Configure Agent container logging driver

- ecs-init/engine/engine.go
> - Fix typo in comment

- scripts/ecs-anywhere-install.sh
- check for invalid or empty cli flags
- support ssm agent installed via ubuntu snap
- check that ssm agent is running when skipping registration
- simplify ssm registration check
- skip gpg package verify if server does not have gpg command available
Some ecs anywhere install script bumps found while testing.
This was tested on:
- ubuntu
- centos
- debian
- sles
NA
> Install script fixups

- scripts/ecs-anywhere-install.sh
- check curl downloads for failures (404, 403, etc.)
- log what script is doing while waiting for agent to startup
- change wording around agent startup wait
- add license info for ssm agent and docker engine
- a couple shellcheck fixes
tested on:
- debian
- ubuntu
- sles
- centos
none
> ECS Anywhere install script fixups

- scripts/ecs-anywhere-install.sh
Address some remaining todos in install script.
Minor updates.
Unit tests in ci.
N/A
> Address some remaining todos in install script.

- ecs-init/docker/docker.go
- ecs-init/docker/docker_test.go
Changes paths so the agent is running at host level
changed docker.go and altered the tests in docker_test.go
This is tested using make test and all the tests pass
yes
> changes in init for mounted volume migration path

- scripts/ecs-anywhere-install.sh
Adds the config variable necessary to run GPU tasks for ECS anywhere. This adds a flag called --enable-gpu to the installation script which will do the following
* Will run nvidia-smi -L which will fail if nvidia drivers are not installed or GPUs are not attached to the instance
* If nvidia-smi -L runs fine, it will add the config var "ECS_ENABLE_GPU_SUPPORT=true" to /var/lib/ecs/ecs.config
* Launched an instance with nvidia drivers and cuda installed and GPUs attached, the instance successfully became part of the ECS-cluster
* Launched an instance with nvidia drivers and cuda installed but no GPUs attached, the installation script failed saying
"NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running." …
> Merge feature ecs-anywhere-gpu support to dev 

- .github/workflows/gitsecrets.yml
[Git secret](https://github.com/awslabs/git-secrets) is a tool scanning commits/commit messages for possible leaks of secret into github.
This pull request add a new github workflow to check the code push and prs. Since git secret is usually installed in dev environment and checking commits when run `git commit`, the way this workflow works is 1) install git secret on worker 2) scan existing code base (instead of individual commits) based on previous clean record to detect problem in the new code changes
New tests cover the changes:  N/A
Tested with a branch in my fork 
* https://github.com/Realmonia/amazon-ecs-init/commits/shishi
Made sure it can fail when git secrets scan failed
* https://github.com/Realmonia/amazon-ecs-init/runs/4478634446?check_suite_focus=true
Add git secret scan to …
> Add git secrets workflow

- scripts/ecs-anywhere-install.sh
This pr makes changes to the ECS Anywhere installation script in order for exec to be supported on ECS Anywhere. Changes already approved in #451 and #461 to the feature branch feature/ecs-anywhere-exec, see those for further detail
See linked pr's for testing details. Also ran though a series of manual tests that tested the feature on different linux distributions.
Add exec prerequisites to ecs-anywhere installation script
> add exec prerequisites to ecs-anywhere installation script

- scripts/ecs-anywhere-install.sh
This change corresponds to updating the SSM Agent version to 3.1.804.0 in [ECS AMI](https://github.com/aws/amazon-ecs-ami/pull/24) as part of customer request.
> Update the SSM Agent version to 3.1.804.0

- ecs-init/engine/engine.go
Logs what the pre-start function in ecs-init is doing, so that us and customers can understand what is taking time during ecs-init package startup. This will log to the ecs service's systemd journal before the agent container starts.
amazon-ecs-init binary was manually built and tested.
Enhancement - Add more granular logging to ecs-init prestart process.
> Log what pre-start is doing
